export default {
  pt: {
    explore: 'Explore',
    everything: 'Tudo',
    alerts: 'Alertas',
    platforms: 'Plataformas',
    news: 'Notícias',
    deals: 'Promoções',
    support: 'Apoie-nos',
    mostAccessed: 'Mais acessadas do dia',
    hello: 'Olá!',
    settings: 'Suas configurações',
  },
  en: {
    explore: 'Explore',
    everything: 'Everything',
    alerts: 'Alerts',
    platforms: 'Platforms',
    news: 'News',
    deals: 'Deals',
    support: 'Support Us',
    mostAccessed: 'Most accessed of the day',
    hello: 'Hello!',
    settings: 'Your settings',
  },
};
