export default {
  pt: {
    explore: 'Explore',
    everything: 'Tudo',
    alerts: 'Alertas',
    platforms: 'Plataformas',
    news: 'Notícias',
    deals: 'Promoções',
    support: 'Apoie-nos',
    mostAccessed: 'Mais acessadas do dia',
    hello: 'Olá!',
    settings: 'Suas configurações',
    favourites: 'Favoritos',
    contact: 'Contate-nos',
    signIn: 'Fazer login',
    signUp: 'Registrar',
    signOut: 'Desconectar',
    registerCtaLabel: 'Novo por aqui? Registre-se',
    details: 'Detalhes',
  },
  en: {
    explore: 'Explore',
    everything: 'Everything',
    alerts: 'Alerts',
    platforms: 'Platforms',
    news: 'News',
    deals: 'Deals',
    support: 'Support Us',
    mostAccessed: 'Most accessed of the day',
    hello: 'Hello!',
    settings: 'Your settings',
    favourites: 'Favourites',
    contact: 'Contact us',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    registerCtaLabel: 'New here? Sign up',
    details: 'Details',
  },
};
